### Array with Numpy

In [55]:
import numpy as np

In [56]:
array_1d=np.array([1,2,3])
print(array_1d)
array_2d=np.array([[1,2,3],[4,5,6]])
print(array_2d)

[1 2 3]
[[1 2 3]
 [4 5 6]]


### Creating Martices

In [57]:
Zeros = np.zeros((4,4))
ones=np.ones((6,6))
print("Zeros array\n",Zeros)
print("ones array\n",ones)
Full=np.full((3,3),9)
print("full array\n",Full)
random=(np.random.random((3,3))*10)
print("random array\n",random)


Zeros array
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
full array
 [[9 9 9]
 [9 9 9]
 [9 9 9]]
random array
 [[3.55176424 8.26180119 0.26433109]
 [9.02248684 6.14496053 2.77295764]
 [3.63231419 9.00353073 0.3770443 ]]


### Array Properties


In [58]:
arr=np.array([[1,2,3],[4,5,6]])
print("Shape",arr.shape)
print("Dimension",arr.ndim)
print("size",arr.size)
print("Data Type",arr.dtype)

Shape (2, 3)
Dimension 2
size 6
Data Type int64


In [59]:
arr=np.array([['A','B','C'],['D','E','F']])
print("Shape",arr.shape)
print("Dimension",arr.ndim)
print("size",arr.size)
print("Data Type",arr.dtype)

Shape (2, 3)
Dimension 2
size 6
Data Type <U1


In [60]:
import numpy as np

arr = np.arange(12)
print("Array:\n", arr)

Reshape = np.reshape(arr, (3, 4))
print("Reshape:\n", Reshape)


Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshape:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Selection in Arrays

In [61]:
arr=np.array([[1,2,3],[4,5,6]])

print("Specific Element ",arr[0,2])
print("Specific Element ",arr[0])
print("Specific Element ",arr[:,1])


Specific Element  3
Specific Element  [1 2 3]
Specific Element  [2 5]


### Sorting

In [62]:
unsorted = np.array([2,5,78,32,1,2,4])
print("Sorted Array :",np.sort(unsorted))

unsorted_2d = np.array([[1,2],[2,3],[3,1]])
print("Sorted Array :",np.sort(unsorted_2d,axis=0))



Sorted Array : [ 1  2  2  4  5 32 78]
Sorted Array : [[1 1]
 [2 2]
 [3 3]]


### Filtering

In [63]:
numbers=np.arange(1,20)
Even_numbers=numbers[numbers % 2 == 0]
print("Even Numbers: \n",Even_numbers)

Odd_numbers=numbers[numbers % 2 != 0]
print("Odd Numbers: \n",Odd_numbers)

## Another Way
mask = numbers > 50
print("Numbers greater than 50 : \n",numbers[mask])



Even Numbers: 
 [ 2  4  6  8 10 12 14 16 18]
Odd Numbers: 
 [ 1  3  5  7  9 11 13 15 17 19]
Numbers greater than 50 : 
 []


### Facing Indexing and Np Where

In [66]:
indices = [0,2,4,6,8,10]
print(numbers[indices])

Np_where=np.where(numbers % 2==0)
print(Np_where)
print("index of even numbers:",numbers[Np_where])

#conditon Array
conditon_array=np.where(numbers>10,numbers*10,numbers*3)
print(conditon_array)
conditon_array=np.where(numbers>10,False,True)
print(conditon_array)

[ 1  3  5  7  9 11]
(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17]),)
index of even numbers: [ 2  4  6  8 10 12 14 16 18]
[  3   6   9  12  15  18  21  24  27  30 110 120 130 140 150 160 170 180
 190]
[ True  True  True  True  True  True  True  True  True  True False False
 False False False False False False False]


### Adding and Removing Elements

In [68]:
a=np.array([[1,2],[2,3]])
b=np.array([[1,2,4],[2,3,3]])
c=np.array([[1,2],[2,3]])

print("Shaped Of Array A and B are same ?",a.shape==b.shape)
print("Shaped Of Array A and C are same ?",a.shape==c.shape)

Shaped Of Array A and B are same ? False
Shaped Of Array A and C are same ? True


In [75]:
#Adding Elements In Row
Orginal=np.array([[1,2,3],[2,3,4]])
new_element=np.array([7,8,3])
Add_row=np.vstack((Orginal,new_element))
print(Add_row)

#Adding Elements In Colume
Orginal=np.array([[1,2,3],[2,3,4]])
new_element=np.array([[7],[8]])
Add_row=np.hstack((Orginal,new_element))
print(Add_row)


[[1 2 3]
 [2 3 4]
 [7 8 3]]
[[1 2 3 7]
 [2 3 4 8]]
