In [1]:
import numpy as np


In [ ]:
Sales=np.array([    [1,120 ,150 , 90 , 75 ,200 ,180],
                    [2,130 ,160 ,100 , 85 ,195, 175],
                    [3,140 ,155, 110 , 95 ,210 ,190],
                    [4,125 ,165, 105 , 80 ,205, 185],
                    [5,135 ,170 ,115  ,90 ,220 ,195],
                    [6,145 ,175 ,120 , 85 ,225, 200],
                    [7,150 ,180, 125, 100 ,230, 205],
                    [8,155 ,185 ,130, 105, 240, 210],
                    [9,160 ,190, 135 ,110 ,250, 215],
                    [10,165, 195 ,140, 115, 260, 220]])
print(Sales)

[[  1 120 150  90  75 200 180]
 [  2 130 160 100  85 195 175]
 [  3 140 155 110  95 210 190]
 [  4 125 165 105  80 205 185]
 [  5 135 170 115  90 220 195]
 [  6 145 175 120  85 225 200]
 [  7 150 180 125 100 230 205]
 [  8 155 185 130 105 240 210]
 [  9 160 190 135 110 250 215]
 [ 10 165 195 140 115 260 220]]


In [16]:

day=np.sum(Sales[:,1:],axis=1)
print(day)

[ 815  845  900  865  925  950  990 1025 1060 1095]


In [17]:
year=np.sum(Sales[:,1:],axis=0)
print(year)

[1425 1725 1170  940 2235 1975]
