### Ek NumPy array banao jisme 1 se 10 tak ke numbers ho.


In [56]:
import numpy as np


In [57]:
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


### 2️⃣ Ek random 3x3 matrix generate karo.

In [58]:
import random
import math

In [59]:
ran=(np.random.random([3,3])*100)
print(ran)

[[19.00356061  2.85846326 53.72134617]
 [10.07788266 55.31566365 24.39671373]
 [65.75005913 20.79448017 85.68543712]]


### 3️⃣ Ek zeroes ka array banao jo shape (4, 4) ho.

In [60]:
zeros=np.zeros([4,4])
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### 4️⃣ Ek identity matrix banao jo size 5x5 ho.

In [61]:
identity = np.indices([5,5])
print(identity)

[[[0 0 0 0 0]
  [1 1 1 1 1]
  [2 2 2 2 2]
  [3 3 3 3 3]
  [4 4 4 4 4]]

 [[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]]


In [62]:
identityMatrix = np.eye(5)
print(identityMatrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Ek array banao 1D array ko 3x3 matrix me reshape karne ke liye.

In [63]:
arr_1d=np.arange(1,10)
Reshaped =np.reshape(arr_1d,([3,3]))
print(Reshaped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
