### 1️⃣ Ek random array banao aur usme se max, min aur mean value find karo.

In [1]:
import numpy as np
import random

In [ ]:
array=(np.random.random(20))*100
print(array)
print(array.max())
print(array.min())
print(array.mean())


[0.18048287 0.14879319 0.38521971 0.71738345 0.60980347 0.17916384
 0.14163275 0.94783768 0.61397617 0.9721788  0.06023498 0.22204385
 0.31696972 0.65164003 0.26572278 0.03459353 0.38092727 0.66087408
 0.18998518 0.72362725]
0.9721788023173427
0.0345935304673497
0.4201545300757904


### 2️⃣ Ek array banao jisme sirf even numbers ho (1 se 50 tak).

In [14]:
EvenArray =np.arange(0,51,2)
print(EvenArray)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50]


### 3️⃣ Ek 1D array ko reverse karo (e.g., [1, 2, 3] ➝ [3, 2, 1]).

In [17]:
array_1d =np.array([1,2,3,4,5,6,7,8,8,9,10])
reversed = array_1d[::-1]
print(reversed)

[10  9  8  8  7  6  5  4  3  2  1]


### 4️⃣ Ek 5x5 matrix banao aur uske diagonal elements extract karo.

In [25]:
array_5d=np.arange(25)
Reshaped = array_5d.reshape(5,5)
print(Reshaped)
print(Reshaped.diagonal().sum())

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
60


### 5️⃣ Ek array ke duplicate values remove karo.

In [30]:
arr = np.array([1,2,3,4,5,2,3,4,2,1,5,6,8,4])
print(arr)
duplicate=np.unique(arr)
print(duplicate)

[1 2 3 4 5 2 3 4 2 1 5 6 8 4]
[1 2 3 4 5 6 8]
